### ISSUE TITLE
Need to URL Decode the query string from the request before parsing into QueryParams

### ISSUE THREAD

**Issue by AllenJensen** [katharsis-project/katharsis-servlet#11]
The QueryStringUtils is not properly decoding the query string prior to parsing and rejects properly formatted requests such as:

/resource/&filter%5Bid%5D=xxxxxxx

Warning message produced:

2015-11-20 10:52:56.327  WARN 4509 --- [nio-9080-exec-4] io.katharsis.invoker.KatharsisInvoker    : Error occurred while dispatching katharsis request. io.katharsis.jackson.exception.ParametersDeserializationException: Malformed filter parameter: %5Bid%5D

bug in source:
 katharsis-servlet/src/main/java/io/katharsis/servlet/util/QueryStringUtils.java

**Comment by AllenJensen** [comment]
Work-around is to extend the ServletKatharsisInvokerFilter with one that overrides the getRequestQueryString method with one that does the URLDecoder.decode. Then create a JsonApiFilter that extends AbstractKatharsisFilter as a Component (BeanFactoryAware) and override the createKatharsisInvokerContext to use the new invoker filter.

**Comment by meshuga** [comment]
I've just realized that some servlet implementations (e.g. Jetty) automatically perform url decoding, so Katharsis should discover if values are already decoded.
